# Generated by Django 5.1.4 on 2025-01-25 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_review_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='film',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.film'),
            preserve_default=False,
        ),
    ]
