# Generated by Django 5.1.4 on 2025-01-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='{% static "images/default_profile_pic.png" %}', upload_to=''),
        ),
    ]
