# Generated by Django 5.1.4 on 2025-01-29 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='/profile_pics/default_profile_pic.png', upload_to='profile_pics/'),
        ),
    ]
