# Generated by Django 5.1.4 on 2025-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Great'), (4, 'Good'), (3, 'Mediocre')], default=3),
            preserve_default=False,
        ),
    ]
