# Generated by Django 5.1.4 on 2025-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_review_tags_film_tags_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, '5 ⭐'), (4, '4 ⭐'), (3, '3 ⭐'), (2, '2 ⭐'), (1, '1 ⭐'), (0, '0 ⭐')]),
        ),
    ]
