# Generated by Django 5.1.4 on 2025-02-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_options_alter_director_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritefilm',
            unique_together={('user', 'film')},
        ),
    ]
