# Generated by Django 5.1.4 on 2025-02-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_favoritefilm_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritefilm',
            unique_together=set(),
        ),
    ]
