# Generated by Django 5.1.4 on 2025-03-17 15:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_favoritefilm_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
