# Generated by Django 5.1.4 on 2025-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_review_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(default='/posters/kill-bill-vol-1-i97652.jpg', null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='/review_headers/dummy_header.png', null=True, upload_to='review_headers/'),
        ),
    ]
