# Generated by Django 5.1.4 on 2025-03-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_film_image_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, default='/posters/dummy_poster.png', null=True, upload_to='posters/'),
        ),
    ]
