# Generated by Django 5.1.4 on 2025-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_film_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, default='posters/dummy_poster.png', null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='review_headers/dummy_header.png', null=True, upload_to='review_headers/'),
        ),
    ]
